name: PR Validation Checks

on:
    pull_request:
        branches:
            - main
            - develop

jobs:
    test:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm ci

            - name: Copy local .env.test
              run: cp /Users/icdominguez/deployments/portfolio_rest_api/shared/.env.test .env.test

            - name: Run unit tests with coverage
              run: npm run test:coverage

            - name: Run integration tests
              run: npm run test:integration
